version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123

  web:
    build: ./config
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  celery:
    build: ./config
    command: celery --app=config worker --loglevel=info
    volumes:
      - ./config:/usr/src/app

    depends_on:
      - web
      - redis

  celerybeat:
    build: ./config
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./config:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine

  dashboard:
    build: ./config
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery
volumes:
  postgres_volume:
