# Generated by Django 4.1.4 on 2022-12-16 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='формат:7XXXXXXXXXX', max_length=11, validators=[django.core.validators.RegexValidator(regex='7\\d{10}')], verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=10, verbose_name='Код оператора')),
                ('timezone', models.CharField(max_length=10, verbose_name='Часовой пояс')),
                ('tag', models.CharField(max_length=50, verbose_name='Произвольная метка')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название рассылки')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('client_filter', models.CharField(help_text='По данному полю будут фильтроваться клиенты', max_length=20, verbose_name='Код оператора или тег')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='send_not.message', verbose_name='Cообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
