# Generated by Django 4.1.4 on 2022-12-16 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='7\\d{10}')], verbose_name='Телефон')),
                ('code', models.CharField(max_length=10, verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=50, verbose_name='Произвольная метка')),
                ('time_zone', models.CharField(help_text='Формат: UCT+01:00', max_length=10, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('client_filter', models.CharField(max_length=20, verbose_name='Фильтр клиентов')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(verbose_name='Статус отправки')),
                ('clients', models.ManyToManyField(related_name='messages', to='send_not.client', verbose_name='Клиенты')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='send_not.mailinglist', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
